# Generated by Django 4.2.1 on 2023-05-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy')], max_length=50, verbose_name='Жанр')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('priсe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, upload_to='static/books/img', verbose_name='Фото книжки')),
                ('full_text', models.TextField(verbose_name='Опис')),
                ('date', models.DateTimeField(verbose_name='Дата публікації')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Книжка',
                'verbose_name_plural': 'Книжки',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookks')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='books.CartItem', to='books.bookks'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
